// Augments the Env interface generated by `wrangler types` with secrets
// supplied via `.dev.vars` (local) or `wrangler secret put` (prod). These
// keys are not declared in wrangler.jsonc, so they do not appear in
// worker-configuration.d.ts.

declare namespace Cloudflare {
	interface Env {
		TIDAL_CLIENT_ID: string;
		TIDAL_CLIENT_SECRET: string;
		// AI Gateway authentication token (cf-aig-authorization). Optional: only
		// needed when the gateway is configured as an Authenticated Gateway.
		AI_GATEWAY_TOKEN?: string;
	}
}
